// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dadaxiaoxiao/account/internal/grpc"
	"github.com/dadaxiaoxiao/account/internal/repository"
	"github.com/dadaxiaoxiao/account/internal/repository/dao"
	"github.com/dadaxiaoxiao/account/internal/service"
	"github.com/dadaxiaoxiao/account/ioc"
	"github.com/dadaxiaoxiao/go-pkg/customserver"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *customserver.App {
	client := ioc.InitEtcdClient()
	db := ioc.InitDB()
	accountDAO := dao.NewAccountGORMDAO(db)
	accountRepository := repository.NewAccountRepository(accountDAO)
	accountService := service.NewAccountService(accountRepository)
	accountServiceServer := grpc.NewAccountServiceServer(accountService)
	cmdable := ioc.InitRedis()
	logger := ioc.InitLogger()
	server := ioc.InitGRPCServer(client, accountServiceServer, cmdable, logger)
	app := &customserver.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdPartyProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitEtcdClient, ioc.InitLogger, ioc.InitOTEL)
